# Quick boot options
sudo: false

# Ignore version tags
branches:
  except:
    - /^v[0-9]/

# Language options
language: node_js
node_js:
  - 4
  - 5

# Coverage report
after_success:
  - export TRAVIS_PASSED=true
  - npm install codeclimate-test-reporter --global
  - codeclimate-test-reporter < coverage/lcov.info
env:
  global:
    # CODECLIMATE_REPO_TOKEN
    - secure: BfmL4mRysi4/qUKuN9Hvx3QsbTRH6XtxfuXj3XXaIQiRNwYAU0FBiVjoJzzKk1AhXmLBzWco3jWFWGY0OpXCnzKLHYYZYB3L/UPGq5aqX004pk2ZaPFO8+nfdua15FP2/7vShB+4FbMTztQO4GZMdOi1QTXOdTJgjISQfIqZ7RIeWEaF3UlySt0Xety9Y2nN3YpdPUIPJW2TWP9dIA/XyMHa9knve7TdPzpXkJelpoi3+EnzEtEUWaPtDTMXwOq4zYM4E1bXeA5ZWPmbA1JlO4lDX1aeOz6MFTmBaPTt8K/TT2PLegh8u6JVyG45R1y8OTKyRPQR4+Dy5vp+NLlSMSugq2lxixcK4tuf17a7zPAAEQLNg7LSR9kg3/gyqjthXa5gMYEVI7kE0+mrJl5stVnkGCJaIBawxr4Miqot6qOkh3JSrv0YKh4q1f+XMgtJFlW4UhtJ5zqp/wRSaQpsWKmGqN6xPRMR//5vrTis7uFuCOvxsAN0wzmjelXuNc2nWLuZsP9A91sTghssdikm9maaiP+keAc4gMxy/GuNf0fqyylcaw+9cY9E4Fsg+0Qlv2p1TPOAmXdr0VIkVAuym8cQr+ULu9w4H1F2YrScYnwThTv9J9jhZXqmVh7Ysh9pTluZoTd9ymgkso0Av5xHN56ltHWF1Sku4FFGmnUdI+Q=

# Npm publish options
deploy:
  provider: npm
  email: i59naga@icloud.com
  api_key:
    secure: wqcQJTafDQ2OtopHdCHLAvW2Y8tH0/TdSqqt9cWzZmZanyYZELn3SSUbW+nRGMUz5uuXwJmjlMyBLGaA5MxP/aw+VZQhLSARX6krfUQa5wwY95W3uSIc0GuUOz5dDfMY1V/duDWi/vhqgKiS3lEZfPN+ij+TEcz0qTmiKd2H6mgsLy9d8L+ewAYh6zvzn4i9bH/wgCBtxhYy2f/fjAfY3x6FQYNgZ4YdClbaJHJEQ8pQYt4AhO2rvNzA/BxDILQpOS9z0QgvzaV7391rufeBAdBaD369Ij1gx5NWkGkJKdZ6xNGV6WLUiFEKG94TBiHbvXo1TpFmT2jnNLJhTfi6e4R3OVlS+v02eYxaIjM8kJ6sxK152ZF3uVba6REz02tup96Xzw2PXhayL0SteRB/uCgrdd7lHiLZmRMfzwAvg4iWYEuWO1FTYDecWUrO/5n2yF2WEYNJdLV4s5afLxen1oboyUX+31uEekIRUGXa1O6fp5A2ZvOjORnx2rTFXH7w0mUaS0YrVLUMTSlR+vS0AglQ9wnbNh+IX7swRQfBJJHxL22wSbS7HRTSBKWVL/Z9UFUzBu9qZWXpc6JvQPFjVNByA9SVbuSpUsn6Vmg2yta980JK5//c6GJymAft11yPaeTPVxpr1EpkTVMOszahvYemmsYlyOU0Bb0U68YHOq4=
  on:
    node: 5